name: sidebar_bigeagle
description: This package adds a Sidebar widget which is convenient for Web & Desktop.
version: 0.2.2+1
homepage: https://github.com/augustt0/sidebar_bigeagle

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: SideBar
      windows:
        pluginClass: SideBar
      web:
        pluginClass: SideBar
        fileName: sidebar_bigeagle_web.dart